# Generated by Django 2.1.5 on 2019-03-12 04:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('API', '0005_auto_20190311_0220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
