# Generated by Django 2.1.5 on 2019-02-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_heading', models.CharField(max_length=250)),
                ('post_body', models.TextField()),
            ],
        ),
    ]
