# Generated by Django 2.1.5 on 2019-03-11 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20190225_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_markdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='privacy_setting',
            field=models.CharField(choices=[('1', 'me'), ('2', 'another author'), ('3', 'my friends'), ('4', 'friends of friends'), ('5', 'only friends on my host'), ('6', 'public')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='posts',
            name='shared_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Posts'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_as', to='API.User'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_bs', to='API.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='API.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_set', to='API.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Posts'),
        ),
    ]
