# Generated by Django 2.1.5 on 2019-03-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='displayname',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
    ]
