# Generated by Django 2.1.5 on 2019-03-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_requests',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
