# Generated by Django 2.1.5 on 2019-03-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_github_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
