# Generated by Django 2.1.5 on 2019-03-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='displayname',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
