# Generated by Django 2.1.5 on 2019-03-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_github_url'),
        ('users', '0003_auto_20190320_0312'),
    ]

    operations = [
    ]
