# Generated by Django 2.1.5 on 2019-03-21 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20190321_0010'),
        ('users', '0002_customuser_friend_requests'),
    ]

    operations = [
    ]
